# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "969c0c2c6d9b335ec96747685efaf54a"
name = "affiliate-event"
handle = "affiliate-event"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "nobu-checkout-extensibility.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
